<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            // Electronics
            [
                'name' => 'Wireless Headphones',
                'description' => 'High-quality wireless headphones with noise cancellation technology. Perfect for music lovers and professionals who need clear audio quality.',
                'price' => 99.99,
                'stock' => 50,
                'image' => 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600',
                'category' => 'electronics',
                'in_stock' => true,
                'rating' => 4.5,
                'reviews_count' => 128,
                'tags' => ['audio', 'wireless', 'noise-cancellation'],
            ],
            [
                'name' => 'Smart Watch',
                'description' => 'Advanced smartwatch with health monitoring features, GPS tracking, and long battery life.',
                'price' => 299.99,
                'stock' => 25,
                'image' => 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600',
                'category' => 'electronics',
                'in_stock' => true,
                'rating' => 4.3,
                'reviews_count' => 89,
                'tags' => ['wearable', 'health', 'fitness'],
            ],
            [
                'name' => 'Laptop Stand',
                'description' => 'Adjustable laptop stand for better ergonomics and improved productivity.',
                'price' => 49.99,
                'stock' => 40,
                'image' => 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=600',
                'category' => 'electronics',
                'in_stock' => true,
                'rating' => 4.1,
                'reviews_count' => 94,
                'tags' => ['office', 'ergonomics', 'accessories'],
            ],
            [
                'name' => 'Bluetooth Speaker',
                'description' => 'Portable speaker with excellent sound quality and long battery life.',
                'price' => 79.99,
                'stock' => 35,
                'image' => 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=600',
                'category' => 'electronics',
                'in_stock' => true,
                'rating' => 4.3,
                'reviews_count' => 112,
                'tags' => ['audio', 'portable', 'bluetooth'],
            ],
            [
                'name' => 'Phone Case',
                'description' => 'Protective case for your smartphone with shock absorption technology.',
                'price' => 29.99,
                'stock' => 75,
                'image' => 'https://images.unsplash.com/photo-1556656793-08538906a9f8?w=600',
                'category' => 'electronics',
                'in_stock' => true,
                'rating' => 4.0,
                'reviews_count' => 78,
                'tags' => ['protection', 'mobile', 'accessories'],
            ],
            [
                'name' => 'Gaming Mouse',
                'description' => 'High-precision gaming mouse with RGB lighting and programmable buttons.',
                'price' => 69.99,
                'stock' => 60,
                'image' => 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=600',
                'category' => 'electronics',
                'in_stock' => true,
                'rating' => 4.4,
                'reviews_count' => 156,
                'tags' => ['gaming', 'mouse', 'rgb'],
            ],
            [
                'name' => 'Mechanical Keyboard',
                'description' => 'Cherry MX switches mechanical keyboard with backlighting.',
                'price' => 129.99,
                'stock' => 45,
                'image' => 'https://images.unsplash.com/photo-1541140532154-b024d705b90a?w=600',
                'category' => 'electronics',
                'in_stock' => true,
                'rating' => 4.6,
                'reviews_count' => 203,
                'tags' => ['keyboard', 'mechanical', 'gaming'],
            ],
            [
                'name' => 'Webcam HD',
                'description' => '1080p HD webcam with autofocus and built-in microphone.',
                'price' => 89.99,
                'stock' => 30,
                'image' => 'https://images.unsplash.com/photo-1587825140708-dfaf72ae4b04?w=600',
                'category' => 'electronics',
                'in_stock' => true,
                'rating' => 4.2,
                'reviews_count' => 87,
                'tags' => ['webcam', 'video', 'conference'],
            ],
            [
                'name' => 'USB-C Hub',
                'description' => 'Multi-port USB-C hub with HDMI, USB 3.0, and SD card reader.',
                'price' => 59.99,
                'stock' => 55,
                'image' => 'https://images.unsplash.com/photo-1593640408182-31c70c8268f5?w=600',
                'category' => 'electronics',
                'in_stock' => true,
                'rating' => 4.1,
                'reviews_count' => 134,
                'tags' => ['usb-c', 'hub', 'adapter'],
            ],
            [
                'name' => 'Wireless Charger',
                'description' => 'Fast wireless charging pad compatible with all Qi-enabled devices.',
                'price' => 39.99,
                'stock' => 80,
                'image' => 'https://images.unsplash.com/photo-1583394838336-acd977736f90?w=600',
                'category' => 'electronics',
                'in_stock' => true,
                'rating' => 4.3,
                'reviews_count' => 95,
                'tags' => ['wireless', 'charging', 'qi'],
            ],

            // Clothing
            [
                'name' => 'Cotton T-Shirt',
                'description' => 'Comfortable cotton t-shirt in various colors. Made from 100% organic cotton.',
                'price' => 24.99,
                'stock' => 100,
                'image' => 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=600',
                'category' => 'clothing',
                'in_stock' => true,
                'rating' => 4.2,
                'reviews_count' => 67,
                'tags' => ['clothing', 'cotton', 'casual'],
            ],
            [
                'name' => 'Denim Jacket',
                'description' => 'Classic denim jacket with vintage wash and modern fit.',
                'price' => 79.99,
                'stock' => 40,
                'image' => 'https://images.unsplash.com/photo-1551028719-001c67cdaec3?w=600',
                'category' => 'clothing',
                'in_stock' => true,
                'rating' => 4.4,
                'reviews_count' => 89,
                'tags' => ['jacket', 'denim', 'casual'],
            ],
            [
                'name' => 'Hoodie',
                'description' => 'Comfortable pullover hoodie with kangaroo pocket and drawstring hood.',
                'price' => 49.99,
                'stock' => 65,
                'image' => 'https://images.unsplash.com/photo-1556821840-3a63f95609a4?w=600',
                'category' => 'clothing',
                'in_stock' => true,
                'rating' => 4.3,
                'reviews_count' => 112,
                'tags' => ['hoodie', 'sweatshirt', 'casual'],
            ],
            [
                'name' => 'Jeans',
                'description' => 'Classic fit jeans with stretch fabric for comfort and durability.',
                'price' => 59.99,
                'stock' => 70,
                'image' => 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=600',
                'category' => 'clothing',
                'in_stock' => true,
                'rating' => 4.1,
                'reviews_count' => 156,
                'tags' => ['jeans', 'denim', 'pants'],
            ],
            [
                'name' => 'Sneakers',
                'description' => 'Comfortable everyday sneakers with cushioned sole and breathable upper.',
                'price' => 89.99,
                'stock' => 85,
                'image' => 'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=600',
                'category' => 'clothing',
                'in_stock' => true,
                'rating' => 4.5,
                'reviews_count' => 203,
                'tags' => ['sneakers', 'shoes', 'casual'],
            ],
            [
                'name' => 'Dress Shirt',
                'description' => 'Professional dress shirt in classic white with button-down collar.',
                'price' => 39.99,
                'stock' => 50,
                'image' => 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=600',
                'category' => 'clothing',
                'in_stock' => true,
                'rating' => 4.2,
                'reviews_count' => 78,
                'tags' => ['shirt', 'formal', 'business'],
            ],
            [
                'name' => 'Summer Dress',
                'description' => 'Lightweight summer dress with floral pattern and comfortable fit.',
                'price' => 69.99,
                'stock' => 35,
                'image' => 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=600',
                'category' => 'clothing',
                'in_stock' => true,
                'rating' => 4.4,
                'reviews_count' => 94,
                'tags' => ['dress', 'summer', 'floral'],
            ],
            [
                'name' => 'Winter Coat',
                'description' => 'Warm winter coat with water-resistant outer shell and cozy lining.',
                'price' => 149.99,
                'stock' => 25,
                'image' => 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=600',
                'category' => 'clothing',
                'in_stock' => true,
                'rating' => 4.6,
                'reviews_count' => 167,
                'tags' => ['coat', 'winter', 'warm'],
            ],
            [
                'name' => 'Baseball Cap',
                'description' => 'Adjustable baseball cap with embroidered logo and curved brim.',
                'price' => 19.99,
                'stock' => 90,
                'image' => 'https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=600',
                'category' => 'clothing',
                'in_stock' => true,
                'rating' => 4.0,
                'reviews_count' => 45,
                'tags' => ['hat', 'cap', 'accessories'],
            ],
            [
                'name' => 'Socks Pack',
                'description' => 'Pack of 6 comfortable cotton socks in various colors.',
                'price' => 14.99,
                'stock' => 120,
                'image' => 'https://images.unsplash.com/photo-1584464491033-06628f3a6b7b?w=600',
                'category' => 'clothing',
                'in_stock' => true,
                'rating' => 4.1,
                'reviews_count' => 89,
                'tags' => ['socks', 'underwear', 'pack'],
            ],

            // Sports & Fitness
            [
                'name' => 'Running Shoes',
                'description' => 'Lightweight running shoes for all terrains. Designed for comfort and performance.',
                'price' => 129.99,
                'stock' => 30,
                'image' => 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600',
                'category' => 'sports',
                'in_stock' => true,
                'rating' => 4.6,
                'reviews_count' => 203,
                'tags' => ['footwear', 'running', 'sports'],
            ],
            [
                'name' => 'Yoga Mat',
                'description' => 'Non-slip yoga mat with carrying strap and alignment lines.',
                'price' => 34.99,
                'stock' => 60,
                'image' => 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=600',
                'category' => 'sports',
                'in_stock' => true,
                'rating' => 4.3,
                'reviews_count' => 134,
                'tags' => ['yoga', 'mat', 'fitness'],
            ],
            [
                'name' => 'Dumbbells Set',
                'description' => 'Adjustable dumbbells set with multiple weight plates and storage rack.',
                'price' => 199.99,
                'stock' => 20,
                'image' => 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600',
                'category' => 'sports',
                'in_stock' => true,
                'rating' => 4.7,
                'reviews_count' => 89,
                'tags' => ['weights', 'dumbbells', 'strength'],
            ],
            [
                'name' => 'Resistance Bands',
                'description' => 'Set of 5 resistance bands with different resistance levels and door anchor.',
                'price' => 24.99,
                'stock' => 75,
                'image' => 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600',
                'category' => 'sports',
                'in_stock' => true,
                'rating' => 4.2,
                'reviews_count' => 156,
                'tags' => ['resistance', 'bands', 'fitness'],
            ],
            [
                'name' => 'Basketball',
                'description' => 'Official size basketball with composite leather cover.',
                'price' => 29.99,
                'stock' => 40,
                'image' => 'https://images.unsplash.com/photo-1546519638-68e109498ffc?w=600',
                'category' => 'sports',
                'in_stock' => true,
                'rating' => 4.4,
                'reviews_count' => 78,
                'tags' => ['basketball', 'ball', 'sports'],
            ],
            [
                'name' => 'Tennis Racket',
                'description' => 'Professional tennis racket with graphite frame and synthetic strings.',
                'price' => 89.99,
                'stock' => 25,
                'image' => 'https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=600',
                'category' => 'sports',
                'in_stock' => true,
                'rating' => 4.5,
                'reviews_count' => 112,
                'tags' => ['tennis', 'racket', 'sports'],
            ],
            [
                'name' => 'Swimming Goggles',
                'description' => 'Anti-fog swimming goggles with UV protection and adjustable straps.',
                'price' => 19.99,
                'stock' => 55,
                'image' => 'https://images.unsplash.com/photo-1530549387789-4c1017266635?w=600',
                'category' => 'sports',
                'in_stock' => true,
                'rating' => 4.1,
                'reviews_count' => 67,
                'tags' => ['swimming', 'goggles', 'water'],
            ],
            [
                'name' => 'Fitness Tracker',
                'description' => 'Waterproof fitness tracker with heart rate monitor and GPS.',
                'price' => 149.99,
                'stock' => 35,
                'image' => 'https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=600',
                'category' => 'sports',
                'in_stock' => true,
                'rating' => 4.6,
                'reviews_count' => 189,
                'tags' => ['fitness', 'tracker', 'health'],
            ],
            [
                'name' => 'Jump Rope',
                'description' => 'Adjustable speed jump rope with weighted handles and tangle-free cable.',
                'price' => 14.99,
                'stock' => 80,
                'image' => 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600',
                'category' => 'sports',
                'in_stock' => true,
                'rating' => 4.0,
                'reviews_count' => 45,
                'tags' => ['jump', 'rope', 'cardio'],
            ],
            [
                'name' => 'Protein Shaker',
                'description' => 'BPA-free protein shaker bottle with mixing ball and leak-proof lid.',
                'price' => 12.99,
                'stock' => 100,
                'image' => 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600',
                'category' => 'sports',
                'in_stock' => true,
                'rating' => 4.3,
                'reviews_count' => 123,
                'tags' => ['protein', 'shaker', 'supplements'],
            ],

            // Home & Kitchen
            [
                'name' => 'Coffee Maker',
                'description' => 'Automatic coffee maker with programmable features and built-in grinder.',
                'price' => 89.99,
                'stock' => 15,
                'image' => 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=600',
                'category' => 'home',
                'in_stock' => true,
                'rating' => 4.4,
                'reviews_count' => 156,
                'tags' => ['kitchen', 'coffee', 'appliance'],
            ],
            [
                'name' => 'Air Fryer',
                'description' => 'Digital air fryer with 4-quart capacity and multiple cooking presets.',
                'price' => 79.99,
                'stock' => 30,
                'image' => 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=600',
                'category' => 'home',
                'in_stock' => true,
                'rating' => 4.5,
                'reviews_count' => 203,
                'tags' => ['kitchen', 'air-fryer', 'cooking'],
            ],
            [
                'name' => 'Blender',
                'description' => 'High-speed blender with 6 blades and 1000W motor for smoothies and soups.',
                'price' => 69.99,
                'stock' => 25,
                'image' => 'https://images.unsplash.com/photo-1585515655854-8a5ef6a4a3f0?w=600',
                'category' => 'home',
                'in_stock' => true,
                'rating' => 4.3,
                'reviews_count' => 134,
                'tags' => ['kitchen', 'blender', 'smoothie'],
            ],
            [
                'name' => 'Vacuum Cleaner',
                'description' => 'Cordless vacuum cleaner with HEPA filter and 40-minute runtime.',
                'price' => 199.99,
                'stock' => 20,
                'image' => 'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=600',
                'category' => 'home',
                'in_stock' => true,
                'rating' => 4.6,
                'reviews_count' => 178,
                'tags' => ['cleaning', 'vacuum', 'cordless'],
            ],
            [
                'name' => 'Smart Speaker',
                'description' => 'Voice-controlled smart speaker with built-in virtual assistant.',
                'price' => 49.99,
                'stock' => 45,
                'image' => 'https://images.unsplash.com/photo-1543512214-318c7553f226?w=600',
                'category' => 'home',
                'in_stock' => true,
                'rating' => 4.4,
                'reviews_count' => 167,
                'tags' => ['smart', 'speaker', 'voice'],
            ],
            [
                'name' => 'LED Strip Lights',
                'description' => 'RGB LED strip lights with remote control and adhesive backing.',
                'price' => 24.99,
                'stock' => 60,
                'image' => 'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=600',
                'category' => 'home',
                'in_stock' => true,
                'rating' => 4.2,
                'reviews_count' => 89,
                'tags' => ['led', 'lights', 'rgb'],
            ],
            [
                'name' => 'Throw Pillows Set',
                'description' => 'Set of 2 decorative throw pillows with removable covers.',
                'price' => 39.99,
                'stock' => 50,
                'image' => 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=600',
                'category' => 'home',
                'in_stock' => true,
                'rating' => 4.1,
                'reviews_count' => 67,
                'tags' => ['pillows', 'decor', 'home'],
            ],
            [
                'name' => 'Desk Lamp',
                'description' => 'Adjustable LED desk lamp with USB charging port and touch control.',
                'price' => 34.99,
                'stock' => 40,
                'image' => 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600',
                'category' => 'home',
                'in_stock' => true,
                'rating' => 4.3,
                'reviews_count' => 112,
                'tags' => ['lamp', 'desk', 'led'],
            ],
            [
                'name' => 'Plant Pot Set',
                'description' => 'Set of 3 ceramic plant pots with drainage holes and saucers.',
                'price' => 29.99,
                'stock' => 35,
                'image' => 'https://images.unsplash.com/photo-1485955900006-10f4d324d411?w=600',
                'category' => 'home',
                'in_stock' => true,
                'rating' => 4.0,
                'reviews_count' => 78,
                'tags' => ['plants', 'pots', 'ceramic'],
            ],
            [
                'name' => 'Bath Towel Set',
                'description' => 'Set of 4 premium cotton bath towels in various colors.',
                'price' => 44.99,
                'stock' => 55,
                'image' => 'https://images.unsplash.com/photo-1584464491033-06628f3a6b7b?w=600',
                'category' => 'home',
                'in_stock' => true,
                'rating' => 4.4,
                'reviews_count' => 145,
                'tags' => ['towels', 'bath', 'cotton'],
            ],

            // Books & Media
            [
                'name' => 'Programming Book',
                'description' => 'Comprehensive guide to modern web development with practical examples.',
                'price' => 49.99,
                'stock' => 30,
                'image' => 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=600',
                'category' => 'books',
                'in_stock' => true,
                'rating' => 4.7,
                'reviews_count' => 89,
                'tags' => ['book', 'programming', 'education'],
            ],
            [
                'name' => 'Cookbook',
                'description' => 'Collection of 100 easy-to-follow recipes for home cooking.',
                'price' => 24.99,
                'stock' => 40,
                'image' => 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=600',
                'category' => 'books',
                'in_stock' => true,
                'rating' => 4.3,
                'reviews_count' => 67,
                'tags' => ['book', 'cooking', 'recipes'],
            ],
            [
                'name' => 'Fiction Novel',
                'description' => 'Bestselling mystery novel with gripping plot and memorable characters.',
                'price' => 16.99,
                'stock' => 60,
                'image' => 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=600',
                'category' => 'books',
                'in_stock' => true,
                'rating' => 4.5,
                'reviews_count' => 123,
                'tags' => ['book', 'fiction', 'mystery'],
            ],
            [
                'name' => 'Self-Help Book',
                'description' => 'Guide to personal development and achieving your goals.',
                'price' => 19.99,
                'stock' => 45,
                'image' => 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=600',
                'category' => 'books',
                'in_stock' => true,
                'rating' => 4.2,
                'reviews_count' => 78,
                'tags' => ['book', 'self-help', 'motivation'],
            ],
            [
                'name' => 'Children\'s Book',
                'description' => 'Illustrated children\'s book with engaging story and colorful pictures.',
                'price' => 12.99,
                'stock' => 80,
                'image' => 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=600',
                'category' => 'books',
                'in_stock' => true,
                'rating' => 4.6,
                'reviews_count' => 156,
                'tags' => ['book', 'children', 'illustrated'],
            ],

            // Beauty & Personal Care
            [
                'name' => 'Skincare Set',
                'description' => 'Complete skincare routine with cleanser, moisturizer, and serum.',
                'price' => 79.99,
                'stock' => 25,
                'image' => 'https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=600',
                'category' => 'beauty',
                'in_stock' => true,
                'rating' => 4.4,
                'reviews_count' => 134,
                'tags' => ['skincare', 'beauty', 'routine'],
            ],
            [
                'name' => 'Hair Dryer',
                'description' => 'Professional hair dryer with ionic technology and multiple heat settings.',
                'price' => 59.99,
                'stock' => 35,
                'image' => 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=600',
                'category' => 'beauty',
                'in_stock' => true,
                'rating' => 4.3,
                'reviews_count' => 89,
                'tags' => ['hair', 'dryer', 'styling'],
            ],
            [
                'name' => 'Makeup Brush Set',
                'description' => 'Professional makeup brush set with 12 brushes and carrying case.',
                'price' => 34.99,
                'stock' => 50,
                'image' => 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=600',
                'category' => 'beauty',
                'in_stock' => true,
                'rating' => 4.5,
                'reviews_count' => 167,
                'tags' => ['makeup', 'brushes', 'tools'],
            ],
            [
                'name' => 'Perfume',
                'description' => 'Luxury fragrance with long-lasting scent and elegant packaging.',
                'price' => 89.99,
                'stock' => 20,
                'image' => 'https://images.unsplash.com/photo-1541643600914-78b084683601?w=600',
                'category' => 'beauty',
                'in_stock' => true,
                'rating' => 4.6,
                'reviews_count' => 203,
                'tags' => ['perfume', 'fragrance', 'luxury'],
            ],
            [
                'name' => 'Face Mask',
                'description' => 'Hydrating face mask with natural ingredients for glowing skin.',
                'price' => 14.99,
                'stock' => 70,
                'image' => 'https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=600',
                'category' => 'beauty',
                'in_stock' => true,
                'rating' => 4.2,
                'reviews_count' => 95,
                'tags' => ['face', 'mask', 'skincare'],
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}
